### ISSUE TITLE
Module timm.models.gluon_resnet not found.

### ISSUE THREAD

**Issue by kairos03** [zhoudaquan/NES#1]
I run your code with google colab.
But, I encounter this error.

Can you help me?

```
Traceback (most recent call last):
  File "train.py", line 28, in <module>
    from timm.data import Dataset, create_loader, resolve_data_config, FastCollateMixup, mixup_target
  File "/content/NES/timm/__init__.py", line 2, in <module>
    from .models import create_model, list_models, is_model, list_modules, model_entrypoint
  File "/content/NES/timm/models/__init__.py", line 3, in <module>
    from .gluon_resnet import *
ModuleNotFoundError: No module named 'timm.models.gluon_resnet'
```

**Comment by zhoudaquan** [comment]
Sure, to the simplest, you can just delete that line if you are not using the gluon model. If you do, just place a model at the imported place. I use the model for testing previous but not uploaded for this repo.

**Comment by webbrain-one** [comment]
Hi there! Thanks for reporting this issue. I've opened a pull request (#3) to fix the `ModuleNotFoundError: No module named 'timm.models.gluon_resnet'` error. The update ensures the `gluon_resnet` module is properly included in the package exports, so your code should run smoothly now. Feel free to check out the PR and let me know if you need any further assistance! 😊
